common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

yolo/urls.py
from django.urls import path
from .views import yolo_base_views, yolo_question_views, yolo_answer_views, yolo_comment_views, yolo_vote_views
# from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'yolo'

urlpatterns = [
    # path('', views.index, name='index'),
    # base_views.py
    path('intro/', yolo_base_views.intro, name='intro'),
    path('intro_mini/', yolo_base_views.intro_mini, name='intro_mini'),
    path('', yolo_base_views.yolo_index, name='yolo_index'),
    path('<int:yolo_question_id>/', yolo_base_views.yolo_detail, name='yolo_detail'),
    # question_views.py
    path('question/create/', yolo_question_views.yolo_question_create, name='yolo_question_create'),
    path('question/modify/<int:yolo_question_id>/', yolo_question_views.yolo_question_modify, name='yolo_question_modify'),
    path('question/delete/<int:yolo_question_id>/', yolo_question_views.yolo_question_delete, name='yolo_question_delete'),
    # answer_views.py
    path('answer/create/<int:yolo_question_id>/', yolo_answer_views.yolo_answer_create, name='yolo_answer_create'),
    path('answer/modify/<int:yolo_answer_id>/', yolo_answer_views.yolo_answer_modify, name='yolo_answer_modify'),
    path('answer/delete/<int:yolo_answer_id>/', yolo_answer_views.yolo_answer_delete, name='yolo_answer_delete'),
    # comment_views.py
    path('comment/create/question/<int:yolo_question_id>/', yolo_comment_views.yolo_comment_create_question, name='yolo_comment_create_question'),
    path('comment/modify/question/<int:yolo_comment_id>/', yolo_comment_views.yolo_comment_modify_question, name='yolo_comment_modify_question'),
    path('comment/delete/question/<int:yolo_comment_id>/', yolo_comment_views.yolo_comment_delete_question, name='yolo_comment_delete_question'),
    path('comment/create/answer/<int:yolo_answer_id>/', yolo_comment_views.yolo_comment_create_answer, name='yolo_comment_create_answer'),
    path('comment/modify/answer/<int:yolo_comment_id>/', yolo_comment_views.yolo_comment_modify_answer, name='yolo_comment_modify_answer'),
    path('comment/delete/answer/<int:yolo_comment_id>/', yolo_comment_views.yolo_comment_delete_answer, name='yolo_comment_delete_answer'),
    # vote_views.py
    path('vote/question/<int:yolo_question_id>/', yolo_vote_views.yolo_vote_question, name='yolo_vote_question'),
    path('vote/answer/<int:yolo_answer_id>/', yolo_vote_views.yolo_vote_answer, name='yolo_vote_answer'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
from ..models import Question
import logging
loger = logging.getLogger('pybo')
# Create your views here.
def index(request):
    loger.info("INFO 레벨로 출력")
    # 입력인자
    page = request.GET.get('page', 1)
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')
    # 정렬
    if so == 'recommend':
        question_list = (Question.objects.annotate(num_voter=Count('voter'))
                         .order_by('-num_voter', '-create_date'))
    elif so == 'popular':
        question_list = (Question.objects.annotate(num_answer=Count('answer'))
                         .order_by('-num_answer', '-create_date'))
    else:   # recent
        question_list = Question.objects.order_by('-create_date')
    # 조회
    # question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()

    # 페이징 처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    return render(request, 'pybo/question_detail.html', context)

yolo/views/yolo_base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
from ..models import YQuestion
import logging
loger = logging.getLogger('yolo')

# Create your views here.
def yolo_index(request):
    # loger.info("INFO 레벨로 출력")
    # 입력인자
    page = request.GET.get('page', 1)
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')
    # 정렬
    if so == 'recommend':
        yolo_question_list = (YQuestion.objects.annotate(num_voter=Count('voter'))
                              .order_by('-num_voter', '-create_date'))
    elif so == 'popular':
        yolo_question_list = (YQuestion.objects.annotate(num_answer=Count('yanswer'))
                              .order_by('-num_answer', '-create_date'))
    else:   # recent
        yolo_question_list = YQuestion.objects.order_by('-create_date')
    # 조회
    # question_list = Question.objects.order_by('-create_date')
    if kw:
        yolo_question_list = yolo_question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(yanswer__author__username__icontains=kw)
        ).distinct()

    # 페이징 처리
    paginator = Paginator(yolo_question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'yolo_question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'yolo/yolo_question_list.html', context)


def yolo_detail(request, yolo_question_id):
    yolo_question = get_object_or_404(YQuestion, pk=yolo_question_id)
    context = {'yolo_question':yolo_question}
    return render(request, 'yolo/yolo_question_detail.html', context)

# yolo 프로그램 개요 설명
def intro(request):
    # yolo_question = get_object_or_404(YQuestion, pk=yolo_question_id)
    # context = {'yolo_question':yolo_question}
    return render(request, 'yolo/intro.html')

# KDT_mini : 별도의 앱을 만들기가 애매해서 yolo에서 처리
def intro_mini(request):
    return render(request, 'yolo/intro_mini.html')

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="shortcut icon" href="{% static 'images/h_favicon.ico' %}">
    <!-- Bootstrap 5 적용 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Hong's Portfolio</title>
</head>
<body>
{% include "navbar_bs5.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/mini_base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="shortcut icon" href="{% static 'images/h_favicon.ico' %}">
    <!-- Bootstrap 5 적용 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Hong's Portfolio</title>
</head>
<body>
{% include "navbar_bs5.html" %}
{% include "mini_title.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/mini_title.html
<p>
<div class="fw-bold text-center fs-2 text-secondary">
        KDT mini Project
</div>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <!--a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a-->
    <a class="navbar-brand" href="{% url 'yolo:yolo_index' %}">AI기반 선박도장품질관리 시스템</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <form action="{% url 'common:logout' %}" method="post">
                    {% csrf_token %}
                    {% if request.user.is_superuser == True %}
                    <input class="nav-link" type="submit" value="{{ user.username }}:(관리자) 로그아웃" />
                    {% else %}
                    <input class="nav-link" type="submit" value="{{ user.username }}:(사용자) 로그아웃" />
                    {% endif %}
                </form>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

templates/navbar_bs5.html
<!-- 네비게이션바 Bootstrap 5-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Hong's Portfolio</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">KDT Final</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'yolo:intro' %}">프로젝트 개요</a></li>
                  <li><a class="dropdown-item" href="{% url 'yolo:yolo_index' %}">프로젝트 시연</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">KDT Advanced</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">추가예정</a></li>
                  <!--li><a class="dropdown-item" href="{% url 'yolo:yolo_index' %}">프로그램 시연</a></li-->
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">KDT mini</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'yolo:intro_mini' %}">프로젝트 개요</a></li>
                  <li><a class="dropdown-item" href="https://bit.ly/4bm3zbV" target="_blank">프로젝트 시연</a></li>
                </ul>
              </li>                         
            <!--li class="nav-item">
            <a class="nav-link" href="#">Link</a>
            </li-->  
        </ul>
      </div>
    </div>
    <!-- 로그인/아웃 -->
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <form action="{% url 'common:logout' %}" method="post">
                    {% csrf_token %}
                    {% if request.user.is_superuser == True %}
                    <input class="nav-link" type="submit" value="{{ user.username }}:(관리자) 로그아웃" />
                    {% else %}
                    <input class="nav-link" type="submit" value="{{ user.username }}:(사용자) 로그아웃" />
                    {% endif %}
                </form>
                {% else %}
                <!--a class="nav-link" href="{% url 'common:login' %}">로그인</a-->
                <form action="{% url 'common:login' %}" method="post">
                    {% csrf_token %}
                    <input class="nav-link" type="submit" value="로그인"/>
                </form>
                {% endif %}
            </li>
        </ul>
    </div>
  </nav>

templates/yolo_base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="shortcut icon" href="{% static 'images/h_favicon.ico' %}">
    <!-- Bootstrap 5 적용 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Hong's Portfolio</title>
</head>
<body>
{% include "navbar_bs5.html" %}
{% include "yolo_title.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/yolo_title.html
<p>
<div class="fw-bold text-center fs-2 text-secondary">
        AI기반 선박도장 품질관리시스템
</div>